title: Front End Development
author: Jyoti
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome to Front End Development.Here, you will learn to make beautiful websites using HTML,CSS and JavaScript.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  JyotiMate # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
